#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Add uploads dir

if [ ! -d ${OPENSHIFT_DATA_DIR}uploads ]; then
    mkdir ${OPENSHIFT_DATA_DIR}uploads
fi

# Add multisite upload dir
#
if [ ! -d $OPENSHIFT_DATA_DIR/blogs.dir ]; then
    mkdir $OPENSHIFT_DATA_DIR/blogs.dir
fi

ln -sf ${OPENSHIFT_DATA_DIR}blogs.dir ${OPENSHIFT_REPO_DIR}php/wp-content/
ln -sf ${OPENSHIFT_DATA_DIR}uploads   ${OPENSHIFT_REPO_DIR}php/wp-content/

set -e

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    exit 5
fi

if [ -z "$OPENSHIFT_MEMCACHED_HOST" ]
then
    echo 1>&2
    echo "Could not find memcached.  Please run:" 1>&2
    echo "rhc add-cartridge http://reflector-getupcloud.getup.io/reflect?github=getupcloud/openshift-origin-cartridge-memcached --app $OPENSHIFT_APP_NAME" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

if [ -z "$OPENSHIFT_MEMCACHED_HOST" ]
then
    exit 5
fi

# Enable w3-total-cache

cp ${OPENSHIFT_REPO_DIR}php/wp-content/plugins/w3-total-cache/wp-content/advanced-cache.php ${OPENSHIFT_REPO_DIR}php/wp-content/
cp ${OPENSHIFT_REPO_DIR}php/wp-content/plugins/w3-total-cache/wp-content/object-cache.php ${OPENSHIFT_REPO_DIR}php/wp-content/

cp -a ${OPENSHIFT_REPO_DIR}.openshift/w3tc-config ${OPENSHIFT_REPO_DIR}/php/wp-content/

oo-erb ${OPENSHIFT_REPO_DIR}/php/wp-content/w3tc-config/master.erb > ${OPENSHIFT_REPO_DIR}/php/wp-content/w3tc-config/master.php

